### ISSUE TITLE
plugin makes QGIS crash

### ISSUE THREAD

**Issue by fchabouis** [ccrook/QGIS-Contour-Plugin#15]
Hello,
I'm using the contour plugin on QGIS 2.10, ubuntu. It's making QGIS crash very often. I don't know if you need a test case as virtually everything I'm trying to do with it fails. Did you notice the same issue ? It may be a problem with my config. Do you have ways to print debug information when the plugin crashes ?
Thanks

**Comment by ccrook** [comment]
Hi.  Sorry you are having problems with the plugin.  Yes .. I definitely need more information, as it is not crashing for me. 

Ideally a small sample data set and QGIS project and the options you used to cause the crash.  Also the version information from the QGIS Help | About dialog, as well as the operating system.   The other useful thing to know is the version of matplotlib you are using.  You can find this by opening the QGIS Python Console (from the Plugin menu) and typing in the lines:

import matplotlib
matplotlib.__version__

Thanks for taking the time to let me know about this issue .. hopefully if you can get me some more information we can fix it.

**Comment by istopopoki** [comment]
Hello,
Here are the requested infos:
QGIS version : 2.10.1-Pisa
OS : Ubuntu 15.04
matplotlib.__version__ : 1.4.2

test case : I click on the contour plugin icon, I select value as the field, I click on "both" lines and filled contour, OK -> instant QGIS crash.

Please find attached a tar.gz folder with the files you asked for. I renamed it as jpg to be allowed to send it. If the trick doesn't work let me know and I will send it differently.

Thanks !

![qgis test case](https://cloud.githubusercontent.com/assets/15341118/10820854/a540c9be-7e4f-11e5-95a7-e63706011fbb.jpg)

**Comment by ccrook** [comment]
Haven't looked at it yet but just to let you know that packaging the test case as a .jpg has worked.
I haven't yet been able to reproduce the issue - I've tried with 2.8 and recent development build (pre 2.12 release), but in both cases the contours were built without any problem (and looked good!).   I haven't got 2.10 available yet, but it feels unlikely that there would be an issue with that.   I'm using an older version of matplotlib - 1.3.1 - but even if that was a problem I'd not have expected it to crash QGIS itself.  Also I'm running ubuntu 14.04 - again I'd not have expected this to cause a problem.  So at the moment I'm at a loss as to why this is a problem.  

Have you been able to contour other data sets - just wondering if this problem is specific to this data or applies to every data set.  Also have you tried different options around rendering.  (maybe without the "apply colours" option ticked)

**Comment by istopopoki** [comment]
Yes, I have been able to get some results.
For example the same test, but checking "contour lines" works. But checking "Filled contour" crashes.
I've tried to uncheck the apply contours, no change.
I've tried to reduce the number of points. If I filter first on values <= 20, everything works fine.

If there is a crash there might be a log file or a core somewhere no ?

**Comment by ccrook** [comment]
Closing stale issue
