### ISSUE TITLE
Contour Labels show the wrong elevation.

### ISSUE THREAD

**Issue by moody1951** [ccrook/QGIS-Contour-Plugin#44]
![image](https://user-images.githubusercontent.com/71227980/94137119-911f0700-fe2b-11ea-8a7f-a8c9fc864c0e.png)

I set up UTM 15 in US feet and contoured an area shown on link above.  Contours look good.  However, the labels show the wrong elevations (grossly wrong).  I change to map units, and the numbers are still wrong. Used the profile plugin to verify contours are correct, but labels are wrong.  This is a major problem.

**Comment by ccrook** [comment]
@moody1951 That sounds very odd..  I can't really comment further without more information - it works for me with a different data set.  If you provide a sample data set that demonstrates the issue (just the points you are contouring), the contour settings you are using, and the QGIS version information (eg from Help | About) then I could see if I can see anything obvious.  Otherwise I can't offer much.

It might be worth checking that the labels match the contours you think they do (ie are not offset a long way from the contour).  Easiest way is to use the info tool to read the label attribute of the contour..

**Comment by moody1951** [comment]
Chris,I figured it out.  It was my mistake.  I was labeling IDs instead of elevations.
I am transitioning from another GIS package and made a mistake.  Thank you for checking.
    On Thursday, September 24, 2020, 03:43:52 PM CDT, Chris Crook <notifications@github.com> wrote:  
 
 


@moody1951 That sounds very odd.. I can't really comment further without more information - it works for me with a different data set. If you provide a sample data set that demonstrates the issue (just the points you are contouring), the contour settings you are using, and the QGIS version information (eg from Help | About) then I could see if I can see anything obvious. Otherwise I can't offer much.

It might be worth checking that the labels match the contours you think they do (ie are not offset a long way from the contour). Easiest way is to use the info tool to read the label attribute of the contour..
